#!/bin/sh
# Wompt Authentication (<%= deployment %> server running in <%= application_environment %> mode)

case $1 in
	start)
    cd <%=current_path%>/authentication
    <%
    env = application_environment
    log_file = "#{shared_path}/log/wompt_auth"
    %>
    exec sudo -u ubuntu rackup --env <%=env%> --pid <%=shared_path%>/pids/wompt_auth.pid 2>><%=log_file%>.error.log 1>><%=log_file%>.log
		 ;;
	 stop)  
		 kill `cat <%=shared_path%>/pids/wompt_auth.pid` ;;
	 *)  
		 echo "usage: wompt_auth {start|stop}" ;;
esac