source "http://rubygems.org"

gem "sinatra"
gem "omniauth", ">= 0.2.0.beta1"
gem "json"
gem "mongomatic"
gem "haml"

# required by one of the above, though not sure why, it's not listed as a dependency in any of the specs
gem "i18n"
